# models.py
from uagents import Model

class CommissionRequest(Model):
    """Model for the initial commission request."""
    client_name: str
    task_description: str
    budget: float
    deadline: str # e.g., "YYYY-MM-DD"

class AgreementDraft(Model):
    """Model for sending the draft agreement generated by ASI-1."""
    commission_id: str
    draft_text: str

class Approval(Model):
    """Model for the client to approve or reject the draft."""
    commission_id: str
    approved: bool

# IMPORTANT: Define the models expected by the TransactAI agent
# Check Ishaan's examples/docs for the EXACT models.
# These are HYPOTHETICAL examples based on the Alice/Bob links.
# You MUST replace these with the actual models from TransactAI docs/examples.

class PaymentRequest(Model):
    """HYPOTHETICAL model to send TO TransactAI to initiate payment."""
    recipient_address: str # The address of the agent to pay (Client Agent)
    amount: float
    denomination: str # e.g., "USD", "FET", check TransactAI docs
    notes: str | None = None

class PaymentNotification(Model):
    """HYPOTHETICAL model received FROM TransactAI by the recipient."""
    sender_address: str
    amount: float
    denomination: str
    status: str # e.g., "COMPLETED", "PENDING", check TransactAI docs
    notes: str | None = None